#ifndef PEA_PWR_LATESTALGORITHMRUN_H
#define PEA_PWR_LATESTALGORITHMRUN_H

enum LatestAlgorithm {
    NONE = 0,
    BRUTE_FORCE = 1,
    BRUTE_FORCE_OPT = 2,
    BRANCH_AND_BOUND = 3,
    DYNAMIC = 4
};

#endif //PEA_PWR_LATESTALGORITHMRUN_H
